# Generated by Django 2.1.1 on 2018-10-23 14:06

from django.db import migrations


def populate_categories(apps, schema_editor):
    EquipmentCategory = apps.get_model('resources', 'EquipmentCategory')

    EquipmentCategory(name='Microscopy').save()
    EquipmentCategory(name='Computer').save()
    EquipmentCategory(name='Fridge').save()



class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            populate_categories,
            migrations.RunPython.noop,
        ),
    ]