# Generated by Django 2.1.4 on 2019-02-08 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='at_building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Building', verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='room',
            name='biosafety_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biosafety.Level'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building_floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Floor', verbose_name='Floor'),
        ),
    ]
