# Generated by Django 2.1.4 on 2019-02-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biosafety', '0001_initial'),
        ('resources', '0005_auto_20190208_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='biosafety_risks',
            field=models.ManyToManyField(to='biosafety.Risk'),
        ),
    ]
