# Generated by Django 2.1.4 on 2019-02-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_resource_biosafety_risks'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='req_access',
            field=models.BooleanField(default=False, verbose_name='Require access'),
        ),
    ]
