# Generated by Django 2.1.4 on 2019-02-13 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_resource_req_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='resource',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='resources.Resource'),
            preserve_default=False,
        ),
    ]
