# Generated by Django 2.1.5 on 2019-02-13 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0008_accessrequest_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='accessrequest',
            name='status_changed',
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.ResourceAccess'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='closed_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='access_closer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='closed_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed on'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='reason',
            field=models.TextField(blank=True, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='requested_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='access_requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='resource',
            field=models.ForeignKey(limit_choices_to={'req_access': True}, on_delete=django.db.models.deletion.CASCADE, to='resources.Resource'),
        ),
    ]
