# Generated by Django 2.1.5 on 2019-02-13 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20190213_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='closed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_closer', to=settings.AUTH_USER_MODEL),
        ),
    ]
