# Generated by Django 2.1.4 on 2019-02-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_auto_20190213_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='access_req',
            field=models.TextField(blank=True, null=True, verbose_name='Access requirements'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='reason',
            field=models.TextField(blank=True, help_text='Why and how you want to access the resource. Describe also if you fulfill the access requirements.', verbose_name='Extra info'),
        ),
    ]
