# Generated by Django 2.1.4 on 2019-02-22 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0011_auto_20190221_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='managers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='reason',
            field=models.TextField(blank=True, help_text='Why and how you want to access the resource. Describe also if you fulfill the access requirements.', verbose_name='Access details'),
        ),
    ]
