# Generated by Django 2.1.4 on 2019-02-22 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0012_auto_20190222_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourceaccess',
            options={'verbose_name': 'Resource access', 'verbose_name_plural': 'Resource accesses'},
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Rejection reason'),
        ),
        migrations.AddField(
            model_name='resourceaccess',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resourceaccess_creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourceaccess',
            name='created_on',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourceaccess',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resourceaccess_revoker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceaccess',
            name='revoked_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Revoked on'),
        ),
    ]
