# Generated by Django 2.1.4 on 2019-02-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_auto_20190222_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrequest',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='resourceaccess',
            name='created_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Created on'),
        ),
    ]
