# Generated by Django 2.1.4 on 2019-02-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_auto_20190222_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourceaccess',
            name='revoked_on',
        ),
    ]
