# Generated by Django 2.1.5 on 2019-02-24 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_remove_resourceaccess_revoked_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceaccess',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='resourceaccess',
            name='resource',
            field=models.ForeignKey(limit_choices_to={'req_access': True}, on_delete=django.db.models.deletion.CASCADE, to='resources.Resource'),
        ),
        migrations.AlterField(
            model_name='resourceaccess',
            name='start_date',
            field=models.DateField(verbose_name='Start'),
        ),
    ]
